{
 "title": "DeepLearingServerMonitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "📃 Redis 큐에 프레임 푸시 소요 시간 (sec)",
   "type": "timeseries",
   "description": "1분간 Redis 큐에 프레임을 넣는 평균 소요 시간(초).",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(redis_queue_push_duration_seconds_sum[1m]) / rate(redis_queue_push_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📷 Redis Queue Length (디바이스별)",
   "type": "gauge",
   "description": "serial_number = chemi-001",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_queue_length{serial_number=\"chemi-001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🙇 추론 요청 수 ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "inference_duration_seconds_count",
     "legendFormat": "inference_requests"
    }
   ]
  },
  {
   "title": "⌚ 평균 추론 소요 시간 (sec)",
   "type": "barchart",
   "description": "누적 추론 시간 / 누적 추론 호출 횟수 (버퍼 단위)\n* 30 프레임 처리하는데 걸리는 평균 시간",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "rate(inference_duration_seconds_sum[5m]) / rate(inference_duration_seconds_count[5m])",
     "legendFormat": "inference_requests"
    }
   ]
  },
  {
   "title": "이벤트 쿨다운 남은 시간",
   "type": "stat",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_cooldown_remaining_seconds{serial_number=\"chemi-001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "✨ 최근 10초 구간 동안의 평균 확률",
   "type": "table",
   "description": "최근 10sec 동안 AI 추론이 출력한 확률들의 평균",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "(\r\n  rate(inference_output_prob_seconds_sum{serial_number=\"chemi-001\"}[10s])\r\n  /\r\n  rate(inference_output_prob_seconds_count{serial_number=\"chemi-001\"}[10s])\r\n)\r\nunless\r\nrate(inference_output_prob_seconds_count{serial_number=\"chemi-001\"}[10s]) == 0\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏲️ 버퍼 추가 처리 시간",
   "type": "timeseries",
   "description": "최근 10sec간 처리 시간 평균 (초)",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(buffer_add_duration_seconds_sum[10s]) / rate(buffer_add_duration_seconds_count[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📏 프레임 버퍼 길이",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 26 },
   "targets": [
    {
     "expr": "frame_buffer_length{serial_number=\"chemi-001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏲️ 이벤트 저장 및 알림 처리 시간 (sec)",
   "type": "stat",
   "description": "최근 10sec 간 이벤트 저장 처리 시간 평균",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(event_save_duration_seconds_sum[10s]) / rate(event_save_duration_seconds_count[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🤸‍♀️ 이벤트 감지 횟수",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_triggered_total", "legendFormat": "fall_events" }
   ]
  }
 ]
}