{
 "title": "streaming server monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "🏿 CPU 사용량 (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "💾 메모리 사용률 ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "💿 디스크 사용률 ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(1 - (sum(node_filesystem_free_bytes{fstype=\"ext4\"}) / sum(node_filesystem_size_bytes{fstype=\"ext4\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📷 현재 접속자 현황 (송출자)",
   "type": "gauge",
   "description": "미디어 서버에 송출하고 있는 카메라 기기 갯수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_producers", "legendFormat": "producer" }
   ]
  },
  {
   "title": "📱 현재 접속자 현황 (송신자)",
   "type": "gauge",
   "description": "미디어 서버에 스트리밍을 요청하는 클라언트 수 ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_consumers", "legendFormat": "consumer" }
   ]
  },
  {
   "title": "🛜 네트워크 사용량",
   "type": "timeseries",
   "description": "초당 수신 바이트 ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "송신"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])\r\n",
     "legendFormat": "수신"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m]) + rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])\r\n",
     "legendFormat": "전체"
    }
   ]
  },
  {
   "title": "⚠️ 원인별 오류",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_errors_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}